import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./components/layout/page";
// import Layout from "../components/Layout"; // Perbaiki jalur impor sesuai struktur proyek Anda

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Layout>
          {children}
        </Layout> */}
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
